# Generated by Django 5.2.3 on 2025-06-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0002_booking_duration_booking_location_booking_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seen_by_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='seen_by_lawyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], max_length=20),
        ),
    ]
