# Generated by Django 5.2.3 on 2025-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapi', '0003_booking_seen_by_client_booking_seen_by_lawyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reschedule_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
