# Generated by Django 5.2.3 on 2025-07-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocateshub', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
