# Generated by Django 5.2.3 on 2025-06-29 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lawyerapi', '0004_lawyer_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating given to the lawyer (1-5 stars).')),
                ('feedback', models.TextField(blank=True, help_text='Optional text feedback for the lawyer.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(help_text='The lawyer being reviewed.', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='lawyerapi.lawyer')),
                ('user', models.ForeignKey(help_text='The user who gave the review.', on_delete=django.db.models.deletion.CASCADE, related_name='given_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lawyer Review',
                'verbose_name_plural': 'Lawyer Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'lawyer')},
            },
        ),
    ]
