# Generated by Django 5.2.3 on 2025-07-10 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapi', '0005_lawyer_average_rating_lawyer_review_count'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(help_text='Reply from the lawyer to the user review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lawyer', models.ForeignKey(help_text='The lawyer replying to the review.', on_delete=django.db.models.deletion.CASCADE, to='lawyerapi.lawyer')),
                ('review', models.OneToOneField(help_text='The review being replied to.', on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reviews.review')),
            ],
            options={
                'verbose_name': 'Review Reply',
                'verbose_name_plural': 'Review Replies',
            },
        ),
    ]
