# Generated by Django 5.2.1 on 2025-06-11 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='profile_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
    ]
