# Generated by Django 5.2.1 on 2025-06-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapi', '0002_alter_lawyer_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='available_slots',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='profile_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
