# Generated by Django 5.2.1 on 2025-06-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapi', '0003_lawyer_available_slots_alter_lawyer_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='languages',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
