# Generated by Django 5.2.3 on 2025-06-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyerapi', '0004_lawyer_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Average rating based on client reviews.', max_digits=3),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='review_count',
            field=models.IntegerField(default=0, help_text='Total number of reviews received.'),
        ),
    ]
