# Generated by Django 5.2.3 on 2025-06-30 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Optional rating given to the website (1-5 stars).', null=True)),
                ('feedback_text', models.TextField(help_text='The detailed feedback provided by the user.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='The user who provided the feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='website_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website Feedback',
                'verbose_name_plural': 'Website Feedback',
                'ordering': ['-created_at'],
            },
        ),
    ]
